# Generated by Django 5.2 on 2025-04-27 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='licence_plate',
            new_name='license_plate',
        ),
    ]
